
server:
  port: 8082

spring:
  application:
    name: ms-order
  datasource:
    url: jdbc:postgresql://postgresql:5432/db_order
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

