version: "3.8"


services:
  postgresql:
    container_name: postgresql
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: db_user
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      ms-net:
    restart: on-failure

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      ms-net:
    restart: on-failure
  ms-auth:
    container_name: ms_auth
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      ms-net:
    restart: on-failure
  ms-user:
    container_name: ms-user
    build:
      context: ./ms-user
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - postgresql
    networks:
      ms-net:
    restart: on-failure
  rabbitmq:
    container_name: rabbit-server
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      ms-net:
        aliases:
          - rabbit
    restart: on-failure
  ms-product:
    container_name: ms-product
    build:
      context: ./ms-product
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
      - rabbitmq
    networks:
      ms-net:
    restart: on-failure
  ms-order:
    container_name: ms-order
    build:
      context: ./ms-order
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgresql
      - rabbitmq
    networks:
      ms-net:
    restart: on-failure

networks:
  ms-net:
    driver: bridge
