
server:
  port: 8084

spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:postgresql://postgresql:5432/db_user
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect